# corona-wrapper-plugin-sample-code

--
------------------------------------------------------------------------  
--                            Wrapper Class                           --
------------------------------------------------------------------------
--
-- v1.5
--
------------------------------------------------------------------------
-- changelog
------------------------------------------------------------------------
--
-- v1.1
-- 1) Fixed errors with content scaling.
-- 2) Added a new feature: you can now use \n for line break
-- 3) In fact of the content-scaling error, alignment can not longer changed with the align function. 
--    Its now fix after initialization.
--
-- v1.2
-- 1) fixed bugs related to the new linebreak feature, should work now without limitations.
--
-- v1.21
-- 1) little corrections
-- 2) added new Parameters for speed tweaking (see parameter list)
--
-- v1.22
-- 1) added fontSizeMax parameter
--
-- v1.23
-- 1) fixed error caused by changes on coronas content-scaling, where size parameters are now relative to the content size.
-- 2) small corrections
--
-- v1.24
-- 1) fixed error caused by missed linebreakes if the string is fetched from a file
--
-- v1.3
-- 1) adaptation to run with current corona versions
-- 2) minor updates
--
-- v1.4
-- 1) maintenance and improvements
--
-- v1.5
-- 1) added justify alignment, updated sample code
--
--
-- last change: 12.03.2017
-- 
------------------------------------------------------------------------
-- Known issues
------------------------------------------------------------------------
--
-- 1. single words, which are wider then the preset-width will not split if no height is set, 
--    width will be adjusted instead.
--
-- 2. In fact that a new text must be wrapped anyway, you have to generate a new object for text changes.
--
------------------------------------------------------------------------
-- Instructions
------------------------------------------------------------------------
--
-- what you get with the newParagraph-function is a normal display-group with text objects inside,
-- so certainly they can handled as those.
--
-- use \n for line breaks
--
-- Study the sample-code and the parameter- and function-List for usage.
--
-- Feel free to contact me, if you have any questions or suggestions.
--
-- If you find a bug, please report it to me. Thanks.
--

